spring:
  jpa:
    generate-ddl: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

  datasource:
    url: jdbc:mysql://localhost:3306/movies?useSSL=false
    username: root
    password: pivotal

  mvc.view:
    prefix: /WEB-INF/
    suffix: .jsp

s3:
  endpointUrl: http://127.0.0.1:9000
  accessKey: NHDRBQWZP60CMABVCA09 
  secretKey: yWlBKXS10I20QR5LFNqRQXCa2j63FHr9502cIcMt
  bucketName: moviefun
